[package]
authors = ["pnlybubbles <pnlybubbles@gmail.com>"]
name = "bvh"
version = "0.1.0"

[dependencies]
bvh = "0.2.1"
flame = "0.2.0"
ordered-float = "0.5.0"
rand = "0.3.18"
time = "0.1.38"
tobj = "0.1.6"
